// File generated by Antigravity to fix Firebase initialization crash.
// Values extracted from google-services.json and GoogleService-Info.plist.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATn3jT3jAIF78CaJiXgCZbW-zDVkMhC68',
    appId: '1:697790023667:web:7f6f1a8c0d1e3a5b2c4d6e', // Placeholder web app ID
    messagingSenderId: '697790023667',
    projectId: 'afyalink-app-cba6f',
    authDomain: 'afyalink-app-cba6f.firebaseapp.com',
    storageBucket: 'afyalink-app-cba6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATn3jT3jAIF78CaJiXgCZbW-zDVkMhC68',
    appId: '1:697790023667:android:80f4f2aaf6143b151df486',
    messagingSenderId: '697790023667',
    projectId: 'afyalink-app-cba6f',
    storageBucket: 'afyalink-app-cba6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjWO41RnW4L0D5HIIZ6gFtM_ccsb4eVJQ',
    appId: '1:697790023667:ios:5dcd613453f0269f1df486',
    messagingSenderId: '697790023667',
    projectId: 'afyalink-app-cba6f',
    storageBucket: 'afyalink-app-cba6f.firebasestorage.app',
    iosBundleId: 'com.afyalink.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjWO41RnW4L0D5HIIZ6gFtM_ccsb4eVJQ',
    appId: '1:697790023667:ios:5dcd613453f0269f1df486',
    messagingSenderId: '697790023667',
    projectId: 'afyalink-app-cba6f',
    storageBucket: 'afyalink-app-cba6f.firebasestorage.app',
    iosBundleId: 'com.afyalink.app',
  );
}
